name: Trigger Azure Pipelines

on:
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

# pr:
#   branches:
#     include:
#     - master

jobs:
  build:
    environment: ADO
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Trigger ADO Pipeline
        uses: Azure/pipelines@v1.2
        with:
          azure-devops-project-url: 'https://dev.azure.com/hpc-platform-team/hpc-image-val'
          azure-pipeline-name: 'hpc-image-val'
          azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
          #azure-pipeline-variables:  '{"variable1": "value1", "variable2": "value2"}' # optional stringified json
